# Site settings
title: Q.Liu 
email: liuqianchao@163.com
description: "Welcome to Q.Liu's Homepage. Here you can find something about my research interests."
baseurl: ""
url: "http://qianchaoliu.github.io/"
twitter_username: liuqianchao
github_username:  qianchaoliu
#({{ site.url }}/assets/
# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]